### ISSUE TITLE
Unsupported Spec Version 

### ISSUE THREAD

**Issue by Data-Nexus** [smith-phil/galasubgraph#10]
On the subgraph that was deployed to the mainnet, it lists a spec version of 0.0.5 (line 1 of the subgraph.yaml file). 

This needs to be downgraded and redeployed for indexers to be able to properly sync. 

Additionally to ensure you have a new IPFS hash for the deployment I would decrement the starting block on line 11 to 10198648.

**Comment by smith-phil** [comment]
Thanks @Data-Nexus, I've approved your pull request for this.
